<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="LAPTOP-CJQ9RU0K" name="FrameworkKekwords.DemoTest" tests="2" failures="1" timestamp="2023-01-05T15:17:47 IST" time="3.455" errors="0">
  <testcase name="verifyTitleTest1" time="3.455" classname="FrameworkKekwords.DemoTest">
    <failure type="java.lang.AssertionError" message="Test case fail zali ka expected [Swag Labs] but found [1Swag Labs]">
      <![CDATA[java.lang.AssertionError: Test case fail zali ka expected [Swag Labs] but found [1Swag Labs]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at FrameworkKekwords.DemoTest.verifyTitleTest1(DemoTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:51)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:41)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifyTitleTest1 -->
  <testcase name="verifyTitleTest" classname="FrameworkKekwords.DemoTest">
    <skipped/>
  </testcase> <!-- verifyTitleTest -->
</testsuite> <!-- FrameworkKekwords.DemoTest -->
